fix: add missing base class 'Enum' (#14)
fixes:

```
src/i2c/emc2101/emc2101_core.py:423: error: Incompatible return value type (got "str", expected "ExternalSensorStatus")  [return-value]
src/i2c/emc2101/emc2101_core.py:426: error: Incompatible return value type (got "str", expected "ExternalSensorStatus")  [return-value]
src/i2c/emc2101/emc2101_core.py:428: error: Incompatible return value type (got "str", expected "ExternalSensorStatus")  [return-value]
```